### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by Hill180** [cncjs/cncjs#129]
connection problems

Hi 

I try to move my homemade CNC from a serial based interfase til USB and Arduino

I have connected a Arduino with GRBL 1.1 loaded onto. Then i have started cncjs and connected the audrino board. I get the status "sucess! all checksums match!"

cool i think. Some functions is gryed out and i can see on the wiki it perhaps i due to connection problems. 

I have tryed to send manuel G codes. they get send but no responce.. 

I have used the windows x64 installer. and have not made any other setup.

Hope some one can help in the right direction thanks 

br
Steen

**Comment by cheton** [comment]
May you check if you're able to see Grbl initialization message after connecting to Arduino. You can check the message from Arduino's serial monitor or from the console widget in cncjs. For example:

```
Grbl 1.1e ['$' for help]
```

Arduino
![image](https://cloud.githubusercontent.com/assets/447801/22789940/9862b152-ef1f-11e6-8292-6147d910c773.png)

cncjs
![image](https://cloud.githubusercontent.com/assets/447801/22790050/ecdc3186-ef1f-11e6-897f-63d1d70bc541.png)

**Comment by Hill180** [comment]
Problem solved, after reinstalling GRBL on Arduino  and the Arduino IDE it worked for some reason. :-)

Cool 

Thanks for the response !!
