### ISSUE TITLE
Recommend Changing GUI Feed & Speed Override Order

### ISSUE THREAD

**Issue by AustinSaintAubin** [cncjs/cncjs#130]
I recommend reordering the Feed & Speed Override order.
(for the people who don't like to play [where's waldo](https://www.google.com/search?q=where%27s+waldo&source=lnms&tbm=isch), look at "F" & "S" overrides "1%", "10%")

From: 
<img width="344" alt="screen shot 2017-02-09 at 8 59 51 pm copy" src="https://cloud.githubusercontent.com/assets/969780/22812609/5674019c-ef0b-11e6-9803-7acc91f34722.png">

To:
<img width="344" alt="screen shot 2017-02-09 at 8 59 51 pm copy" src="https://cloud.githubusercontent.com/assets/969780/22812663/af0bf634-ef0b-11e6-9a52-e01a658de79d.png">

This groups the increase & decrease together, putting the lowest denominations next to each other.

**Comment by cheton** [comment]
Sure. I will change it by today.

**Comment by cheton** [comment]
I use a smaller icon size for 1% and -1%, that will be easy to differentiate between 1% and 10% at first glance.

![image](https://cloud.githubusercontent.com/assets/447801/22851965/e5183762-f06c-11e6-9389-8ff36b704b26.png)

**Comment by cheton** [comment]
Fixed in 1.9.0-alpha.1
