### ISSUE TITLE
Operating the spindle controls should send a feedhold or warning (low priority)

### ISSUE THREAD

**Issue by andrewismoody** [cncjs/cncjs#138]
Operating the spindle control buttons in the Spindle Widget (M3, M4, M5) should probably send a feedhold.  Not sure on sequencing here.  At the very least, I think, turning the spindle off (M5) should trigger a warning if the job is still in progress.  Or maybe I'm not thinking about this correctly.

Low priority.

**Comment by cheton** [comment]
It probably make sense to trigger a warning. I'd like to hear feedbacks on how others think about it :)

**Comment by AustinSaintAubin** [comment]
Triggering a feedhold if M5 is triggered would have saved so many bits... and peaces of work. I would say it should hold the feed if Button is pressed or if spindle off is detected. However, for laser work there should be a easy way to disable feed hold and warnings... and have the setting state saved. This might be part of a bigger Laser Mode state/settings.

- Austin St. Aubin (sent from mobile)

**Comment by cheton** [comment]
How about disabling these buttons in the Spindle widget when a job has started? it can be enabled again when entering either "Idle" or "Hold" state, which means you have to trigger a <kbd>Feed Hold</kbd> or click on the pause button from the UI.

**Comment by andrewismoody** [comment]
Perfect!

**Comment by cheton** [comment]
Fixed in v1.9.0-alpha.4. I will publish an alpha release to NPM later.
