### ISSUE TITLE
ShuttleXpress Problems to configure Buttons

### ISSUE THREAD

**Issue by mwcnc** [cncjs/cncjs#143]
I have Problems to configure the Button 5 - "Switch Jog Distance" and to configure the Jog  in the ShuttleXpress Control Panel under Windows 7. Other Buttons are ok. Can anyone tell me how to program theese keys "=" "[" "]" or can anyone export the settings for cncjs?

Thanks
Matthias

**Comment by cheton** [comment]
#### Button 5
![image](https://cloud.githubusercontent.com/assets/447801/23802202/84826116-05ed-11e7-9b57-eaad6c97d944.png)

#### Jog Forward
![image](https://cloud.githubusercontent.com/assets/447801/23802308/dc6b57de-05ed-11e7-8235-9fcfc288cb38.png)

#### Jog Backward
![image](https://cloud.githubusercontent.com/assets/447801/23802241/abe9e760-05ed-11e7-8b03-1a3cf68ed157.png)

**Comment by mwcnc** [comment]
Hello Cheton,

thanks for your help. I solved the problem. In German-Keyboard-Layout it is impossible to configure the Buttons because you have to press "Shift + 0" to get the "=" and "AltGR + 8" to get the "[", respective "AltGr + 9" to get "]". Temporary switching to US-Keyboard-Layout was an easy way to configure the Buttons.

**Comment by cheton** [comment]
Thank you for letting me know the keyboard layout issue. I will try adding customizable keyboard mapping support in a later release.

**Comment by cheton** [comment]
Hi @mwcnc,

Now you can try 1.9.0-beta.1, it provides additional keyboard shortcuts for ShuttleXpress.
 
*  Select Jog Distance
   <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>cmd</kbd> + <kbd>d</kbd>
* Jog Forward
    <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>cmd</kbd> + <kbd>f</kbd>
* Jog Backward
    <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>cmd</kbd> + <kbd>b</kbd>
* Select A-axis
    <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>cmd</kbd> + <kbd>a</kbd>

**Comment by mwcnc** [comment]
Hi Cheton,

I programmed my ShuttleXpress with the new shortcuts and
tested it with the Version 1.9.0-beta.1 and it works great.

Thank you for your Information and the great program.

Greetings from Germany
Matthias

**Comment by slimline33** [comment]
for easy programming use the virtual keyboard inside Windows! Just a hint for the other ones!
