### ISSUE TITLE
Feedhold & Cycle Start NOT working (v1.9.0-beta)

### ISSUE THREAD

**Issue by AustinSaintAubin** [cncjs/cncjs#145]
The Feedhold & Cycle Start buttons on the top are not working as of (v1.9.0-beta)

**Comment by cheton** [comment]
An error occurred while clicking on the <kbd>Feedhold</kbd> and <kbd>Cycle Start</kbd> button. I will fix it soon by today.

![image](https://cloud.githubusercontent.com/assets/447801/23931080/223c5fb2-096b-11e7-86ed-b6f9ea0d9a37.png)

**Comment by cheton** [comment]
Fixed in 1.9.0-beta.1
