### ISSUE TITLE
Feature Request: Webcam Rotate

### ISSUE THREAD

**Issue by nkings10** [cncjs/cncjs#148]
Hey,

I'm using CNCJS with a MJPG-Streamer and am unable to rotate the webcam feed and the way it has to be mounted is upside down.

It would be great if a simple rotate option to the wiget were added.

Currently i'm using a Chrome plugin for custom css styles where i can force a rotate of the div that holds the img element.

Thanks,

**Comment by nkings10** [comment]
![screenshot 2017-03-19 21 47 56 copy](https://cloud.githubusercontent.com/assets/9352121/24080562/e5d19fca-0ced-11e7-8d72-a1037a1c2d03.jpg)

You can see here when i rotate it like this and hover the mouse over the element is actually upside down. But it works fine. Would just be great if the widget had this option.

**Comment by cheton** [comment]
Sure. I will add two options that allows you to flip the video vertically as well as horizontally to make correction.

- [ ] Flip the video vertically 
- [ ] Flip the video horizontally

**Comment by nkings10** [comment]
Perfect, that will allow for people who may be getting mirrored feeds from cameras too. Covers all basis. Thanks for all your hard work. Do you have a donation link.

**Comment by cheton** [comment]
This feature is now available in [1.9.0-rc](https://github.com/cncjs/cncjs/releases/tag/v1.9.0-rc). You can rotate left, rotate right, flip vertically, or flip horizontally.

![image](https://cloud.githubusercontent.com/assets/447801/24184707/40ad8f44-0f0a-11e7-885a-bccdca8a7925.png)

If you'd like to donate, there is a donation link at the bottom of the README. Thank you.
https://github.com/cncjs/cncjs#donate
