### ISSUE TITLE
GRBL Console some ideas to improve

### ISSUE THREAD

**Issue by xpix** [cncjs/cncjs#149]
I checked cncjs and i love it, here some ideas to make it better
- sometimes the console doesn't scroll in fullscreenmode
- put the input field on the bottom side or better emulate a console screen w/o extra input textbox
- no history feature in input box, (arrow up, get the latest command)

I used windowsdesktop cncjs 1.9.0-rc.1

**Comment by cheton** [comment]
Thank you for your suggestion. That's also what I would like to improve in the near future.

**Comment by cheton** [comment]
xterm.js contains full feature set for terminal emulation. I will give it a try someday.
https://github.com/sourcelair/xterm.js/blob/master/demo/main.js

**Comment by cheton** [comment]
Terminal history is now supported in 1.9.6
