### ISSUE TITLE
G-code widget not showing gcode commands...

### ISSUE THREAD

**Issue by hublerdesignworks** [cncjs/cncjs#152]
I am using cncjs version 1.9.1 in Windows 10 (desktop) and TinyG2.

In the G-code widget, I cannot see the list of gcode commands at the bottom of the widget.

I've looked at several places on the internet on how to turn on the gcode list. Am I missing something?

Help!

**Comment by mayhem2408** [comment]
@hublerdesignworks Just click on the 3d view button to turn off the 3d view and enable the gcode view

![cncjs v1 9 1 3d view](https://cloud.githubusercontent.com/assets/4693903/24636833/4b31e3a0-1920-11e7-9d1a-a87d6540907d.PNG)

![cncjs v1 9 1 gcode view](https://cloud.githubusercontent.com/assets/4693903/24636853/601da0c4-1920-11e7-894c-d22f1c8919cc.PNG)

**Comment by cheton** [comment]
@hublerdesignworks 

Just as @mayhem2408 said, you can click on the <kbd>3D View</kbd> button to toggle between 3D view and gcode view. So far the G-code widget doesn't have much to do, I may deprecate this widget and integrate it into the center view in 2.0 or a future version.
