### ISSUE TITLE
Widgets Not Movable / Reorganise

### ISSUE THREAD

**Issue by AustinSaintAubin** [cncjs/cncjs#155]
v1.9.3 & v1.9.2 
Unable to move / reorganise widgets.

**Comment by cheton** [comment]
I set a delay of 300ms click & hold to prevent accidental sorting especially for touch screen scrolling. Should you be able to sort widgets after a 300ms delay?

**Comment by cheton** [comment]
How about adding a sorting icon aside the title? It will be much clear this icon is intended for sorting, and it can prevent accidental sorting when scrolling with touch screen.

See below:
![image](https://cloud.githubusercontent.com/assets/447801/25416104/8a6165b4-2a6e-11e7-945d-33183b211f65.png)

**Comment by AustinSaintAubin** [comment]
I like that Idea a lot. Might also be good to have widget deletion confirmation or delay.

The delay seems to be acting a lot longer than 300ms... seems like 1000ms.
Using Chrome Version 57.0.2987.133 (64-bit) on Mac OS

**Comment by cheton** [comment]
The delay can be removed after adding the sorting icon. I will also add a confirmation asking user if he would like to remove this widget.

**Comment by cheton** [comment]
Fixed in 1.9.4
