### ISSUE TITLE
Multiple webcam widgets

### ISSUE THREAD

**Issue by cheton** [cncjs/cncjs#158]
Some users have both the Raspberry Pi camera as well as a USB camera, and they would like to have both running and see multiple video sources on the web interface.

A better solution to this is to provide the ability to fork a widget, and the forked widget will have its own settings without interfering with original widget.

**Comment by dirtdiver9** [comment]
Thank you for this!
I have the PI Camera watching the whole machine and a usb endoscope watching the bit directly.  Being able to have both on the screen at once would be great.

**Comment by cheton** [comment]
It will be available soon in v1.9.5. You can fork a widget to use different configuration settings.
