### ISSUE TITLE
G-Code list view renders "<" as html

### ISSUE THREAD

**Issue by fragmuffin** [cncjs/cncjs#178]
Comments are rendered as unsafe HTML.

For example, the gcode:

    G90 G98 F50
    (expanded: <GCodeDrillingCyclePeck: G83{Q1, R2, X9, Y-10.5, Z-12.3}>)
    G00 X9 Y-10.5

will render in the gcode list as:

* G90 G98 F50
* (expanded: )
* G00 X9 Y-10.5

**Comment by cheton** [comment]
Thank you for reporting this issue. The bug has been fixed in the master branch, and the fix will be included in the next release. 😃

**Comment by fragmuffin** [comment]
Oh! That's excellent news.

Thank you

**Comment by cheton** [comment]
Fixed in 1.9.7
