### ISSUE TITLE
Additional Events

### ISSUE THREAD

**Issue by bensuffolk** [cncjs/cncjs#180]
Hi,

I use raspberry pi GPIO to switch power to me stepper motors, and I was looking for the best way to include these into the Cncjs (which I have just found and looks awesome. I'm still building my machine so not actually run any jobs with it yet).

I saw issue 84 which allows you to have external scripts running from the building, or events. This looks like the perfect solution, but it would be great if there was another event  or two:

1. when the system starts (e.g. Everything is running and ready for web connections)

2.  successful connection to the controller (grbl in my case) via the serial port

3. when the serial port is disconnected from the controller.

Regards

Ben

**Comment by cheton** [comment]
Added in 1.9.7
