### ISSUE TITLE
ShuttleXpress + RaspberryPi

### ISSUE THREAD

**Issue by kikolobo** [cncjs/cncjs#183]
Hi All.

Quick question. Is there a more detailed guide on how to configure ShuttleXpress to work with CNCJS in RASPI?

Is it hooked to the client computer or to the raspberry pi server? If so, where do I get drivers and how do I setup? Cant find readable info on my searches.

**Comment by cheton** [comment]
@kikolobo 

ShuttleXpress should be connected to your laptop or desktop computer running browser, you can find the driver at https://www.contourdesign.com/support/drivers/

To configure jog dial, shuttle wheel, and buttons, simply follow the instructions at  https://github.com/cncjs/cncjs/wiki/User-Guide#contour-shuttlexpress to specify keyboard shortcuts for your ShuttleXpress.

**Comment by AustinSaintAubin** [comment]
It is possible to make a [cncjs pendant](https://github.com/cncjs/cncjs-pendant-boilerplate) with ShuttleXpresss, or to use [Node-RED](https://nodered.org/) to connect to cncjs web socket and use Node-Red [hidstream](https://www.npmjs.com/package/hidstream) to make actions based on ShuttleXpress input to the raspberry pi. So you could use any HID device to controller cncjs from the raspberry pi.

**Comment by AustinSaintAubin** [comment]
See [cncjs-pendant-keyboard](https://github.com/cncjs/cncjs-pendant-keyboard) created by @nsfilho 
A simple pendant (using wireless keyboard or usb) to CNCJS
Might work with ShuttleXpress or could be made to work with ShuttleXpress.

**Comment by kikolobo** [comment]
Thank you for this!
