### ISSUE TITLE
Losing Saved Settings

### ISSUE THREAD

**Issue by GeerGuy** [cncjs/cncjs#185]
Sometimes I lose the widgets that I previously selected and the other settings, like the Probe values and Jog settings.  They are reset to defaults when the program is started again.  

Using Windows 7 and CNCJS 1.97, but I have seen it happen with previous versions as well, maybe since 1.90.

**Comment by cheton** [comment]
If you're running the app built with Electron, try removing the <b>%AppData%\cncjs</b> directory (e.g. <b>c:\Users\Username\AppData\Roaming\cncjs</b>) and try again. I guessed there might be a file permission issue with your folder settings.

If you're using a web browser, make sure your browser is not in "Incognito Mode" (i.e. private browsing), or the localStorage settings won't persist after closing the browser.

**Comment by GeerGuy** [comment]
I will try that, thanks.

**Comment by cheton** [comment]
I had ever encountered issue that cncjs cannot store system settings to `c:\Users\<Username>\.cncjs` on a Windows desktop due to incorrect permissions. Everything works fine after removing this file.

**Comment by cheton** [comment]
Sometimes the localStorage won't persist after refreshing or closing the window.

Related issues: https://github.com/electron/electron/issues/1731, https://github.com/cncjs/cncjs/issues/41

**Comment by cheton** [comment]
Found something strange in CNCjs 1.9.8, sometimes it will throw an error on app start when parsing the `c:\Users\<Username>\AppData\Roaming\cncjs\cnc.json` file, this file was used to persist local storage settings to disk (issue #41).

![image](https://user-images.githubusercontent.com/447801/29750565-6b0ac9c8-8b74-11e7-9573-c2be63daf6a2.png)

**Comment by cheton** [comment]
Fixed the bug using a debounced function and synchronous file writing (e.g. `fs.writeFileSync`), that will definitely fix the issue that caused a broken JSON output (https://github.com/cncjs/cncjs/commit/3ddb776fb7784a1eb266fe4afcf0968624251bdd)

![image](https://user-images.githubusercontent.com/447801/29755782-9bd19392-8bcf-11e7-8667-9801f762bf8f.png)

**Comment by cheton** [comment]
Added a commit that will prompt the user for the corrupted workspace settings on program startup

![image](https://user-images.githubusercontent.com/447801/29782220-47414b54-8c4e-11e7-9c8e-f8d005cb49e7.png)

**Comment by cheton** [comment]
Fixed in 1.9.9

See CNCjs 1.9.9 release notes at https://github.com/cncjs/cncjs/releases/tag/v1.9.9
