### ISSUE TITLE
Installation on linux failed

### ISSUE THREAD

**Issue by NervenCid** [cncjs/cncjs#187]
For Linux system i got this error:

npm ERR! code EINTEGRITY
npm ERR! sha512-FJjCmponv4KCYLkZGYqd7L2cO4mmfjTgo6nlFO7G/V/Z9iP+fDgJvuA0/daALQGJ18aFGyduS4Ep1JkusQC62A== integrity checksum failed when using sha512: wanted sha512-FJjCmponv4KCYLkZGYqd7L2cO4mmfjTgo6nlFO7G/V/Z9iP+fDgJvuA0/daALQGJ18aFGyduS4Ep1JkusQC62A== but got sha512-MPigyuJsnbli1XJurgkdfYQn7u3OU1hwth69yA2abJfixUk9mbsrknT0JvI/RmDEnC+Jt/B80M8tHyGFZNuRNQ==. (442997 bytes)

**Comment by nsfilho** [comment]
I use cncjs in Linux without problem. If you could, please, send a little more information, i.e. whats version of your npm? linux version? full command-line?

**Comment by cheton** [comment]
Similar to https://github.com/cncjs/cncjs/issues/172

**Comment by NervenCid** [comment]
@nsfilho 

I'm using Raspbian  STRETCH  with a raspberry pi 3.

I tryed using 

>npm install -g cncjs

and 

>sudonpm install -g cncjs

But both failed

**Comment by cheton** [comment]
@NervenCid 

You can find a complete setup guide for RPi 3 at https://github.com/cncjs/cncjs/wiki/Raspberry-Pi-Setup-Guide#install-cncjs

For my personal preference, I recommend using [Node Version Manager](https://github.com/creationix/nvm) to install Node.js, it allows you to install NPM packages under user home, so you don't need to deal with system directory permissions.

If you're using the system default Node.js, you need to append `--unsafe-perm` during installation, like so: 

```
sudo npm install -g cncjs@latest --unsafe-perm
```

**Comment by cheton** [comment]
Run `npm install npm@latest -g` to install npm 5.4.2 will fix this issue.

https://github.com/cncjs/cncjs/issues/172#issuecomment-336237332
