### ISSUE TITLE
Set all Axis's to Zero button on the main screen interface instead of hidden in sub menu

### ISSUE THREAD

**Issue by markcr** [cncjs/cncjs#198]
#### Description

Feature Request - It would be great to bring the Button to zero all axis's to the front gui as its a high use button that seems hidden away. Nested into the Go to Work Zero buttons would be the most ideal spot.

Fantastic work in cncjs its the perfect solution to work with my new xcarve.

#### Versions

- CNCjs: 1.9.9
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by kikolobo** [comment]
+!

**Comment by cheton** [comment]
Now you can configure custom MDI buttons with CNCjs 1.9.13.

#### Custom Commands

Go to **Axes Settings** to add custom commands and enable manual data input (MDI) support.

![image](https://user-images.githubusercontent.com/447801/35484157-05d67dfe-0487-11e8-8d12-1d519611d075.png)

Toggle MDI mode

![image](https://user-images.githubusercontent.com/447801/35484169-4137892e-0487-11e8-8077-935c30db0321.png)
