### ISSUE TITLE
Tinyweb pendant plugin for windows desktop version?

### ISSUE THREAD

**Issue by markcr** [cncjs/cncjs#199]
#### Description

Is it possible to access the tinyweb pendant web (https://github.com/cncjs/cncjs-pendant-tinyweb/releases) plugin using the electron windows desktop version? - I could'nt find a way to install it similar to the raspberry pi instructions?

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
It's doable, but it requires you to open the Developer Tools and check the server listen port (e.g. 12345) from the Network tab, then you can access to the pendant UI via http://127.0.0.1:12345/pendant.

I will add shortcut support to the top menu that allows you to open a new browser window for the mounted folder, that will be much easier to access the pendant UI.

**Comment by markcr** [comment]
Fantastic - sounds great look forward to seeing it :)

**Comment by cheton** [comment]
[1.9.10 release notes](https://github.com/cncjs/cncjs/releases/tag/v1.9.10)

![image](https://user-images.githubusercontent.com/447801/30726781-7952d696-9f7f-11e7-8fc4-5e49c7d1f9cf.png)
