### ISSUE TITLE
Axes labeled in cm in mm mode

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#205]
#### Description

In mm mode, the Visualizer axis grid has a 10 mm (i.e. 1 cm) pitch, but the axis number labels are in cm (1, 2, 3, ...).  That's confusing, since all other numbers (GCode limits, DROs, etc) are displayed in mm.

#### Versions

- CNCjs: 1.9.9
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [x] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [x ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
Fixed in 1.9.10
