### ISSUE TITLE
change/feature request move machine zero and move work zero

### ISSUE THREAD

**Issue by amx1** [cncjs/cncjs#210]
Dear Cheton,

there are two things I would like to propose to change. The first one is quite simple. TinyG2 M100 gcode uses a comment ({..}) as argument. This will always be deleted before sending in sender.js.

The second one is a bit more a question of implementation strategy. I like the function to configure the machine home and work home gcode sequences. The actual implementation has two drawbacks. The config is stored on client side. You have to configure each client individually and reconfigure after a cache delete of the browser. The second one is that you have to hard code the sequence in additional modules like a pendant (I am working on  a custom pendant). My proposal is to implement these functions as commands of the controller. I tested this for TinyG  and introduced a "machine_home" command which then sends the same sequence for all modules. The configuration should be saved in .cncrc    

#### Description
* feature request: sender.js - TinyG2 M100 ({..}) commands, arguments will be removed
delete function: Remove anything inside the parentheses '()'
see also: https://github.com/synthetos/g2/wiki/Mcodes M100, M100.1, M101

* feature request: 
  1. instead of hard coding in gui, implement "move machine zero", "move work zero", ... as functions of controller
  2. store custom commands for 1) in .cncrc and not on client side

#### Versions

- CNCjs: 1.9.10
- Node.js: 8.4.0
- NPM: 5.4.2

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [ ] Grbl
- [ ] Smoothieware
- [x] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

**Comment by cheton** [comment]
https://github.com/cncjs/cncjs/releases/tag/v1.9.11

Fixed in 1.9.11

**Comment by cheton** [comment]
Reopen this case since the second item (i.e. move machine zero & move work zero) was not implemented in 1.9.11

**Comment by cheton** [comment]
Now you can configure custom MDI buttons with CNCjs 1.9.13.

#### Custom Commands

Go to **Axes Settings** to add custom commands and enable manual data input (MDI) support.

![image](https://user-images.githubusercontent.com/447801/35484157-05d67dfe-0487-11e8-8d12-1d519611d075.png)

Toggle MDI mode

![image](https://user-images.githubusercontent.com/447801/35484169-4137892e-0487-11e8-8077-935c30db0321.png)

**Comment by amx1** [comment]
Dear Cheton 

perfect! Thank you very much.

Axel

**Comment by justinclift** [comment]
Oh wow.  Hadn't realised custom commands are possible.  That's excellent.

Definitely something I'll be trying out too. :smile:

**Comment by amx1** [comment]
Dear Justin,

 

I saw that you are working on g2core too. I checked out the latest g2core edge version, because of step polarity. My custom board needs an active low step signal and up to now,  I changed the stepper routine accordingly. The edge version runs fine and I don´t have to patch the stepper files anymore.

 

There is one bug maybe. I am not able to change the output of the status report. CNCJS sends during the initialization phase a long {“sr”:{“line”:t, …}} command, but this is ignored by g2core/edge. In my case, I did not compile reporting of posx, posy, posz as default option and {“sr”:{“posx”:t,…}} is not working. Therefor the work position is not shown in CNCJS and the tool is not moving. Do you have the same behaviour of g2core? 

 

Best


Axel

 

Von: Justin Clift <notifications@github.com> 
Gesendet: Montag, 21. Mai 2018 16:06
An: cncjs/cncjs <cncjs@noreply.github.com>
Cc: amx1 <amx2203@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [cncjs/cncjs] change/feature request move machine zero and move work zero (#210)

 

Oh wow. Hadn't realised custom commands are possible. That's excellent.

Definitely something I'll be trying out too. 😄

**Comment by justinclift** [comment]
@amx1 Heh Heh Heh.  Already saw your issue report about it on the g2 repo.  Replied there a few minutes after you created it. :wink:

I haven't had a chance to look into it yet.  A major issue came up with a different project which I'm having to sort out now.
