### ISSUE TITLE
File download link in G-Code view does not work

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#211]
#### Description

When a G-Code program is loaded and the visualizer is in G-Code view (not 3D View), the name of the G-Code file is formatted as a link that can be clicked.  Clicking on it invokes the URL

  &lt;host:port&gt;/api/gcode/download?port=&lt;serial port name&gt;

which replaces the cncjs browser windows with a page that says:

  No Unauthorized Acces

Going back from that page to the cncjs window closes the serial connection.

#### Versions

- CNCjs: 1.9.10
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [x] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
https://github.com/cncjs/cncjs/releases/tag/v1.9.11

Fixed in 1.9.11
