### ISSUE TITLE
Documentation fixup for Node versions

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#221]
Several documents, including cncjs's README.md and Raspberry Pi Setup Guide on the wiki, say
```
nvm install 4
nvm use 4
```
Naively following those steps, as I did before I became more familiar with the Node ecosystem, can cause lots of problems that are hard to recover from.  If your system already has Node v6, downgrading to v4 can break npm rather badly.  Now that the latest dev release of Node is 8.7, mentioning v4 is probably a bad idea.

**Comment by erpalma** [comment]
By the way, with node v8 I have had no issues.

**Comment by AustinSaintAubin** [comment]
I will try to fix documentation this weekend.

**Comment by AustinSaintAubin** [comment]
[Documentation](https://github.com/cncjs/cncjs/wiki) should be up-to-date now.
