### ISSUE TITLE
M06 not recognized like M6 

### ISSUE THREAD

**Issue by neilferreri** [cncjs/cncjs#226]
#### Description

Some CAM software generates an M06 rather than an M6 for a tool change.  The M06 just throws an error instead of displaying tool change prompts.

#### Versions

- CNCjs: 1.9.11
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?
- [ ] Download the CNCjs Desktop Application

#### CNC Controller
- [x] Grbl

#### Hardware
- [ ] Desktop or Laptop

#### Operating System
- [ ] Windows

**Comment by cheton** [comment]
It will be fixed in gcode-parser@1.3.4
https://github.com/cncjs/gcode-parser/commit/d21fff198d4062a1ba52b384a81c93273c8d6a52

**Comment by cheton** [comment]
Fixed in [1.9.12](https://github.com/cncjs/cncjs/releases/tag/v1.9.12)
