### ISSUE TITLE
Web Cam Question

### ISSUE THREAD

**Issue by cmcdermi** [cncjs/cncjs#247]
#### Description
Hello,
I am new to cncjs, linux, raspberry pi and CNC in general but have had much luck getting most everything up and running thanks to the excellent documentation provided on this site (THANK YOU). The only problem I am running into at the moment is that the picamera 1.3 board that I have on hand does not seem to be recognized as a valid webcam. This is the picam which connects to the on-board ribbon connector not via usb. I am able to confirm the camera is working through a python script. Is  the picam not usable in this scenario? Does this only work with standard usb webcams? /Dev/video* does not exist.

I was following the directions on this webpage until I got the following: 

/tmp/mjpg-streamer/mjpg-streamer-experimental $ /usr/local/bin/mjpg_streamer -i "input_uvc.so -r 1280x720 -d /dev/video0 -f 30 -q 80" -o "output_http.so -p 8080 -w /usr/local/share/mjpg-streamer/www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: (null)
 i: Desired Resolution: 1280 x 720
 i: Frames Per Second.: 30
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
 i: init_VideoIn failed

 

#### Versions

- CNCjs: 1.9.12
- Node.js: 6.x (not sure everything was updated today)
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [ ] Grbl
- [x] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment]
You might want to take a look at [How to Stream the PiCamera to your Browser](http://desertbot.io/how-to-stream-the-picamera/) & [Webcams known to work](https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work).

Once you know the mjpg-streamer setting you need, take a look at [CNCjs Wiki: MJPEG-Streamer Install & Setup](https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-MJPEG-Streamer-Install-&-Setup-&-FFMpeg-Recording)
