### ISSUE TITLE
Cant open Website from another pc

### ISSUE THREAD

**Issue by nerathul** [cncjs/cncjs#253]
#### Description
I just installed CNCjs 1.9.12 yesterday and had already some problems which i had fixed.
Now I just can't open the webinterface of the pi in the browser of other pc's. Also the Arduino gets not listed as the AMAO its listed as ttyUSB0 and needs the Baudrate 9600 insteadof 152000 just to conect. I have the newest version of GRBL on it (I think it's the 9.*)

#### Versions

- CNCjs: 1.9.12
- Node.js: 7.10.1
- NPM: 5.6.0

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [] Windows
- [ ] Mac
- [x ] Linux

**Comment by cheton** [comment]
You can check this FAQ if you're using the GPIO serial device on a Raspberry Pi.
https://github.com/cncjs/cncjs/wiki/FAQ#raspberry-pi-error-opening-serial-port-ttyama0
