### ISSUE TITLE
Jump to tool changes?

### ISSUE THREAD

**Issue by Sloppsta** [cncjs/cncjs#254]
#### Description
Is it possible to add a feature to jump to different tool changes in the gcode?

For instance, I create gcode to mill a PCB it has 3 different "tool changes". 1 for trace isolation, another for solder mask clearing, and finally to mill holes and cut out dimension.

Usually the solder mask tool change is placed last but Id prefer to do it on the second. So it would be great If I were able to mill the isolation traces, jump to the 3rd tool change (solder mask clearing) then jump to the second (cut out / mill holes).

This is also usefull when you decide you need to mill deeper .01mm and redo that one portion.

Also, +1 for autolevel!

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
Hi @Sloppsta 

To learn how to define tool change positions in a tool change macro, you can refer to the wiki page:
https://github.com/cncjs/cncjs/wiki/Tool-Change
https://github.com/cncjs/cncjs/wiki/Tool-Change#21-tool-change-macro-wcs

If I'm not mistaken your description, I suggest you split your single G-code file into 3 pieces and load them separately for trace isolation, solder mask clearing, and milling holes, which allows you to do the same job again like milling deeper.
