### ISSUE TITLE
Probe is generating an ALARM every time ???

### ISSUE THREAD

**Issue by hublerdesignworks** [cncjs/cncjs#255]
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.13
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application (Windows 64)

#### CNC Controller

- [ ] Grbl
- [ ] Smoothieware
- [x] TinyG/g2core (g2 100.26)

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows 10
- [ ] Mac
- [ ] Linux

Scratching my head for a couple of days and still I can't figure this out. I'm getting an ALARM every time when using the PROBE feature. To my understanding, the Z-AXIS is supposed to move down and trigger the Z-MIN signal wired to the grounded plate and retract. All of the HOMING (XYZ) functions work fine. Umm? What am I missing here? 

Thanks in advance.

**Comment by ril3y** [comment]
I think you need to post your config for g2 also.

**Comment by cheton** [comment]
If you still have problems with Z-probe, you can post your console logs or raise your issue at https://github.com/synthetos/g2/issues
