### ISSUE TITLE
Load gcode without serial connection

### ISSUE THREAD

**Issue by pchanial** [cncjs/cncjs#256]
### Description

If I am not mistaken, it is not possible to load a gcode file before establishing a serial connection.
It would be nice to be able to visualize the gcode toolpaths without such a connection.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [ ] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment]
One option is to use a low cost Arduino clone board and load GRBL on it.
https://m.banggood.com/ATmega328P-Nano-V3-Controller-Board-Compatible-Arduino-p-940937.html?gmcCountry=USD&currency=USD

**Comment by cheton** [comment]
Duplicate of #114

**Comment by arsdragonfly** [comment]
See [This GRBL simulator](https://github.com/grbl/grbl-sim)

**Comment by emcniece** [comment]
Closing as duplicate!
