### ISSUE TITLE
-H does not reflect in logging output correct listening address

### ISSUE THREAD

**Issue by ril3y** [cncjs/cncjs#282]
#### Description

-H command does not log to the correct address:  I suspect to see listening on 0.0.0.0 vs 127.0.0.1 etc.

pi@NanoPi-NEO-Plus2:~$ cncjs -H **0.0.0.0** --controller g2core
2018-02-17T03:45:56.623Z - info: init Loading configuration from "/home/pi/.cncrc"
2018-02-17T03:45:57.810Z - info: init Starting the server at http://**127.0.1.1**:8000

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core
-[ x] NA
#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
The address 0.0.0.0 for servers mean "all IPv4 addresses on the local machine". If a host has two IP addresses, 127.0.0.1 and 192.168.1.1, and the CNCjs server running on the host is configured to listen on 0.0.0.0, it will be reachable at both of those IP addresses.
