### ISSUE TITLE
please add 4th and  5th axis control

### ISSUE THREAD

**Issue by nesquik011** [cncjs/cncjs#283]
#### Description

please add 4th and  5th axis control
and post processors please ? thats a huge problem i dont know how to edit 
#### Versions

- CNCjs: 1.9.14
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [] Grbl
- [x] Smoothieware
- [x] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
Duplicate of #276
