### ISSUE TITLE
"Select Jog Distance" calling incorrect action?

### ISSUE THREAD

**Issue by jgwl** [cncjs/cncjs#287]
#### Description

"Select Jog Distance" (ctrl+alt+cmd+=) doesn't seem to do anything for me. This keycombo triggers JOG_LEVER_SWITCH. In src/web/widgets/Axes/index.jsx, JOG_LEVER_SWITCH is calling this.actions.selectDistance(distance), which doesn't seem to exist. Should it actually be this.actions.selectStep instead?

Also, it would be very nice to have a greater multiple enabled: 
const distances = ['10', '1', '0.1', '0.01', '0.001', ''];

#### Versions

- CNCjs: 1.9.14
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] C.H.I.P
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
Fixed in v1.9.15

Toggle distance: <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>=</kbd>
Increase distance: <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>+</kbd>
Decrease distance: <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>-</kbd>
