### ISSUE TITLE
Running Production Build errors????

### ISSUE THREAD

**Issue by hublerdesignworks** [cncjs/cncjs#288]
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.15
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

Please bear with me...

I am using Git Bash and followed the instructions below...

Running Production Build

$ npm install  # Ensure that packages are installed
$ npm run prepare
$ ./bin/cnc -vv
  :  :  :
Server is listening on 0.0.0.0:8000

What I did...
1. npm install in the cncjs-master directory - fail
2. npm install in the cncjs-master/src directory - ok

3. npm run prepare in the cncjs-master directory - fail 

This is the result...

Duane@DESKTOP-TCI8GAO MINGW64 ~/downloads/cncjs-master
$ npm run prepare

> cncjs@1.9.15 prepare C:\Users\huble\downloads\cncjs-master
> npm run clean && npm run lint && npm run test && npm run build

> cncjs@1.9.15 clean C:\Users\huble\downloads\cncjs-master
> bash -c 'rm -rf ./dist ./output'

> cncjs@1.9.15 lint C:\Users\huble\downloads\cncjs-master
> npm run eslint && npm run stylint

> cncjs@1.9.15 eslint C:\Users\huble\downloads\cncjs-master
> eslint --ext .js --ext .jsx *.js src bin test

Cannot find module 'eslint-config-standard'
Referenced from: C:\Users\huble\downloads\cncjs-master\src\node_modules\consolidate\.eslintrc
Error: Cannot find module 'eslint-config-standard'
Referenced from: C:\Users\huble\downloads\cncjs-master\src\node_modules\consolidate\.eslintrc
    at ModuleResolver.resolve (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:471:25)
    at load (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:542:26)
    at configExtends.reduceRight (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:403:28)
    at loadFromDisk (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:514:22)
    at Object.load (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config\config-file.js:550:20)
    at Config.getLocalConfigHierarchy (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config.js:228:44)
    at Config.getConfigHierarchy (C:\Users\huble\Downloads\cncjs-master\node_modules\eslint\lib\config.js:180:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cncjs@1.9.15 eslint: `eslint --ext .js --ext .jsx *.js src bin test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cncjs@1.9.15 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huble\AppData\Roaming\npm-cache\_logs\2018-02-28T16_19_18_829Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cncjs@1.9.15 lint: `npm run eslint && npm run stylint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cncjs@1.9.15 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huble\AppData\Roaming\npm-cache\_logs\2018-02-28T16_19_18_860Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cncjs@1.9.15 prepare: `npm run clean && npm run lint && npm run test && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cncjs@1.9.15 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huble\AppData\Roaming\npm-cache\_logs\2018-02-28T16_19_18_907Z-debug.log

Duane@DESKTOP-TCI8GAO MINGW64 ~/downloads/cncjs-master
$

Notice: Cannot find module 'eslint-config-standard'...

I need guidance please.

Thanks.

**Comment by cheton** [comment]
You should not run "npm install" in the src/ directory, or it will cause "eslint-config-standard" error as stated above.
