### ISSUE TITLE
Expand Z-Probe widget for x and y axis

### ISSUE THREAD

**Issue by ENGR-mike** [cncjs/cncjs#290]
Cheton,
I would love to see the Z-Probe widget expanded to include X-Probe and Y-Probe.  I copied the G code from the Z-Probe widget and created macros that work just fine.  Unfortunately, whenever I want to change a parameter I have to manually edit the macros.  I like how I can just enter values in the fields for Z-Probe and wish I could do the same for the x and y axis.

**Comment by cheton** [comment]
May I know if there is anything different (excluding the Axis word) in your macros between X/Y probe and Z probe?

**Comment by ENGR-mike** [comment]
No, nothing is different.

**Comment by cheton** [comment]
ok. I will find a way to add X/Y probe support in addition to Z probe.

**Comment by GeerGuy** [comment]
ENGR-mike - can you share your macros for X and Y probe?

**Comment by ENGR-mike** [comment]
The following is for the X axis using a 1/4" bit:
`; X-Probe
G91
G38.2 X0.5 F1
G90
; Set the active WCS X0
G10 L20 P1 X-0.125
; Retract from the material
G91
G0 X-0.1
G90`

The following is for the Y axis using a 1/4" bit:
`; Y-Probe
G91
G38.2 Y0.5 F1
G90
; Set the active WCS Y0
G10 L20 P1 Y-0.125
; Retract from the material
G91
G0 Y-0.1
G90`

**Comment by ENGR-mike** [comment]
Any updates?

**Comment by cheton** [comment]
@ENGR-mike  I'm really busy with my day work over these two months. I will get back to it once I'm free. Sorry for the late.

**Comment by jakeface1** [comment]
I know it’s been a while, but any updates on this feature? Cncjs is by far the best app I’ve used. This would complete it for me.

**Comment by cheton** [comment]
This feature is available in [1.9.21](https://github.com/cncjs/cncjs/releases/tag/v1.9.21)

**Comment by ENGR-mike** [comment]
Thank you so much for implementing this feature.  I greatly appreciate it.  I have been using my macros successfully, but it is nice to have this as a built-in feature. Sent from Mail for Windows 10 From: Cheton WuSent: Friday, March 6, 2020 8:52 PMTo: cncjs/cncjsCc: ENGR-mike; MentionSubject: Re: [cncjs/cncjs] Expand Z-Probe widget for x and y axis (#290) Closed #290.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ENGR-mike** [comment]
It doesn’t work correctly.  I will explain later. Sent from Mail for Windows 10 From: Cheton WuSent: Friday, March 6, 2020 8:52 PMTo: cncjs/cncjsCc: ENGR-mike; MentionSubject: Re: [cncjs/cncjs] Expand Z-Probe widget for x and y axis (#290) Closed #290.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
