### ISSUE TITLE
"An unexpected error has occurred" in settings

### ISSUE THREAD

**Issue by muxa** [cncjs/cncjs#313]
#### Description

When opening settings under "My Account", "Commands", "Events" there's an error displayed: `An unexpected error has occurred.`. The same error is displayed when trying to add a command.

#### Versions

- CNCjs: 1.9.15 for Mac
- Node.js: 8.1.0
- NPM: 5.7.1

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [x] Mac
- [ ] Linux

**Comment by cheton** [comment]
It's probably a permission issue while trying to access the `~/.cncrc` file. I recommend you use NPM installation on Mac, that will be easier to troubleshoot by running `cnc -vvv` to enable verbose output.
