### ISSUE TITLE
Desktop Application shows 'Not found' error on Ubuntu machine

### ISSUE THREAD

**Issue by zfmaster** [cncjs/cncjs#320]
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

#### Detail Info

- I downloaded compiled Electron app from https://github.com/cncjs/cncjs/releases 
- App version: cncjs-app-1.9.15-linux-amd64.deb
- OS: Ubuntu 18.04 and 17.10

![selection_168](https://user-images.githubusercontent.com/10129233/39396459-38d32a8e-4af7-11e8-85b9-dfa803204e49.jpg)
![selection_169](https://user-images.githubusercontent.com/10129233/39396458-389e300e-4af7-11e8-9125-6604c5933692.jpg)

**Comment by sstefanov** [comment]
On my Debian unstable is the same.

**Comment by zfmaster** [comment]
@sstefanov , Thx! Run it as app is much more comfortable than to install nodejs. Now it works for me also, but I think it's still sort of a bug and it need or be fixed or information should be added to installation instructions.

**Comment by splitn2** [comment]
Hi, @sstefanov @zfmaster  , can you please help me I have the same symptoms and for the life of me cannot get it to run using the appimage method, I tried both the .14 and .15 releases and cleaned up afterwards when uninstalling, neither version worked and nothing I tried with permisisons on the main image file helped - what did you guys do to rectify this ? cheers

**Comment by cheton** [comment]
See https://github.com/cncjs/cncjs/issues/347#issuecomment-402619732

**Comment by cheton** [comment]
Fixed in PR #348 

You can try the prebuilt image and let me know the result:
https://github.com/cncjs/cncjs/releases/tag/319-320-347-sessions-latest

**Comment by cheton** [comment]
Fixed in [1.9.16](https://github.com/cncjs/cncjs/releases/tag/1.9.16)
