### ISSUE TITLE
NPM: JSON error, cannot install

### ISSUE THREAD

**Issue by openbuilds-engineer** [cncjs/cncjs#326]
#### Description

Followed https://cnc.js.org/docs/rpi-setup-guide/

#### Versions

CNCJS: None: Fails at sudo npm install -g cncjs@latest --unsafe-perm
```
pi@BIGCNC:~ $ npm -v
node 4.2.0
pi@BIGCNC:~ $ node -v
v7.10.1
```

#### How Do You Install CNCjs?

- [x] NPM sudo npm install -g cncjs@latest --unsafe-perm
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

Irrelevant

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

SCREENSHOT 
![pi error](https://user-images.githubusercontent.com/31449271/39921188-3dfaaa50-551a-11e8-839f-079cca345b3e.JPG)

EDIT: update 
I deleted /root/.npm/cncjs and then reran, now I get:

![same](https://user-images.githubusercontent.com/31449271/39921716-433efb90-551c-11e8-8503-43841e41b3c5.JPG)

so looks like this install itself has an issue, not CNCjs. Closing accordingly

**Comment by cheton** [comment]
Try updating npm installer itself to the latest version (6.x), and removing the cache (~/.npm/) before installing CNCjs again.

```sh
$ npm i -g npm
$ rm -rf ~/.npm/
```

**Comment by openbuilds-engineer** [comment]
Removing cache did the trick. Thanks, we can close this one

**Comment by AustinSaintAubin** [comment]
Added this problem and solutions to Wiki: https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Package-Manager-*(Recommended)*#json-error
