### ISSUE TITLE
Minor note about desktop app installation in OS X

### ISSUE THREAD

**Issue by brucedesertrat** [cncjs/cncjs#330]
#### Description

Running the desktop app for the first time in OS X, simpler process

#### Versions

Any unsigned OS X app can be run the first time without disabling gatekeeper (as shown in your documentation) by navigating to the ap in the Applications folder, control- or right-clicking on it and selecting 'Open' Instead of getting the 'This app is unsigned' error and not running, you will be told the App is unsigned, do you want to run it?:

![screen shot 2018-05-18 at 1 25 40 pm](https://user-images.githubusercontent.com/2592168/40256424-419fae50-5a9f-11e8-860c-c28d685bec61.png)

![screen shot 2018-05-18 at 1 25 56 pm](https://user-images.githubusercontent.com/2592168/40256436-4aca148e-5a9f-11e8-9d1c-e38311409c33.png)

This is safer than changing the Gatekeeper prefs, because it's stupidly easy to forget to set them back, and is the preferred method per Apple's Gatekeeper documentation 

https://support.apple.com/en-us/HT202491

**Comment by cheton** [comment]
It looks much better than changing Gatekeeper options. Would you mind updating the wiki page with the preferred method? Thank you.
https://github.com/cncjs/cncjs/wiki/electron-app#important-notice

**Comment by cheton** [comment]
Updated in the wiki page.
