### ISSUE TITLE
raspberry pi model B+ offline installation help

### ISSUE THREAD

**Issue by nesquik011** [cncjs/cncjs#331]
hello i am new with raspberry pi , is there away to download the files from github then manuilly install it from raspberry pi's RASPBIAN STRETCH WITH DESKTOP ? if yes someone help

**Comment by AustinSaintAubin** [comment]
I recommend that you have an active internet connection durring the install & setup.
After setup is complete, you no longer have to stay online.

-------------------------------------------------------------
There is no easy way to conduct installs offline for everything.
![image](https://user-images.githubusercontent.com/969780/40285877-c08590b8-5c66-11e8-8540-06aacde64155.png)

**Comment by nesquik011** [comment]
I installed online before but i want to install offline anyway ?

Sent from my iPhone

On May 21, 2018, at 2:52 AM, Austin St. Aubin <notifications@github.com<mailto:notifications@github.com>> wrote:


I recommend that you have an active internet connection durring the install & setup.
After setup is complete, you no longer have to stay online.

________________________________

There is no easy way to conduct installs offline for everything.
[image]<https://user-images.githubusercontent.com/969780/40285877-c08590b8-5c66-11e8-8540-06aacde64155.png>

**Comment by cheton** [comment]
@nesquik011 
You may have to turn back to the solution of creating a pre-installed image (https://github.com/cncjs/cncjs/issues/310), and flash the image to the SD card. This is only useful when you want to do volume installation, not one-time installation.

**Comment by nesquik011** [comment]
@cheton   so thats the only way ?

**Comment by cheton** [comment]
Just like @AustinSaintAubin said, it's recommended that you have an active Internet connection for the initial setup.
