### ISSUE TITLE
marlin artcam

### ISSUE THREAD

**Issue by michel83lebois** [cncjs/cncjs#336]
#### Description
Goodmorning everyone. I can not generate a gcode with artcam that is interpretable by anet a8 .... marlin to usarel a printer as a cnc engraver. can anyone help me?
Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment]
You need to generate G-Code from ArtCAM. Look for [ArtCAM GRBL Post Processors](https://forums.autodesk.com/t5/artcam-forum/post-processor-for-grbl/td-p/7154267).
