### ISSUE TITLE
Inventables Carvey: G28.3 Z0 error:20 (Unsupported command)

### ISSUE THREAD

**Issue by brainstorm** [cncjs/cncjs#341]
#### Description

When clicking the zero out machine icon, the command above does not work on a Carvey firmware:

https://github.com/inventables/gCarvin

I have to manually enter `G92 X0 Y0 Z0` command [from Chillipeppr's jpadie](http://chilipeppr.com/jpadie):

<img width="1277" alt="skarmavbild 2018-06-08 kl 17 18 53" src="https://user-images.githubusercontent.com/175587/41144486-6aff5cc6-6b40-11e8-8391-80aad2a6ae14.png">

#### Versions
```bash
$ cncjs --version
1.9.15
$ node --version
v9.5.0
$ npm --version
5.6.0
```
#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [x] Mac
- [ ] Linux

**Comment by neilferreri** [comment]
G28.3 is not a grbl command. I think it's used with tinyG.
G92 Z0 is a temporary offset.
G10 L20 P1 Z0 will give you a persistent offset (stored in memory).
Both are available as selections in the axes widget.

**Comment by brainstorm** [comment]
The `G28.3` command was triggered by clicking the zero axis button in the axes widget.. I expected that widget to send Grbl command since I was connected to a Grbl-compatible machine (Carvey)?

All the other commands seem to work fine, but that's a good point, maybe the Carvey is somehow detected as tinyG by cncjs?

**Comment by brainstorm** [comment]
What are "modal groups" exactly, btw? Seems like those are the "machine presets stored in memory (eeprom)"?:

<img width="334" alt="skarmavbild 2018-06-08 kl 17 18 42" src="https://user-images.githubusercontent.com/175587/41642570-025e373a-74ac-11e8-885c-16474929a891.png">

Perhaps I can override that `G28.3` glitch for grbl somehow modifying some configuration file?

**Comment by MitchBradley** [comment]
Modal groups are GCode state variables that affect the interpretation of subsequent GCode commands.  The "persist" only during the execution of one GCode program.  They are not "persistent" in the usual sense of retaining their values across system power cycles.

Many well-constructed GCode programs include a "safe" line near the top to establish specific settings for them, just in case the program that just ran had used different settings.  Even if the current program is the first to run after powering-up the machine, it is a good idea to explicitly establish the right settings, in case the machine's default settings happen to be wrong for your program.

For example, all of my programs start with at least "G20" or "G21" to set the units.  I used to run them on a Mach3 system that defaulted to inches (G20), while I now run them on a cncjs/tinyg system that defaults to mm (G21).  Most post-processors automatically include a "safe line" that sets even more things explictly.

**Comment by neilferreri** [comment]
@brainstorm grbl does not support resetting **machine** zero. The carvey has homing switches for that.  What are you trying to do?  I'm guessing you're trying to set your work position with the G10 L20 command.
That said, @cheton, the commands below are unsupported by grbl.
![image](https://user-images.githubusercontent.com/2966894/41691538-14ea022c-74c9-11e8-91e3-69f547a934c8.png)
@brainstorm, don't click those.

**Comment by brainstorm** [comment]
Thanks @neilferreri! I was just clicking one of those two buttons, can't remember which one:

<img width="97" alt="skarmavbild 2018-06-26 kl 16 25 43" src="https://user-images.githubusercontent.com/175587/41893015-a3e76940-795d-11e8-86ab-7610a52548f2.png">

And the console displayed the `G28.3 Z0` unsupported command show above. I guess that [Axes/DisplayPanel.jsx](https://github.com/cncjs/cncjs/blob/a0d914eb0160f91326482c87ebfc30ff4242313f/src/web/widgets/Axes/DisplayPanel.jsx) template (and perhaps other elements) are not being updated accordingly when Grbl backend is working? I wish I knew react better to track state/props :-S

**Comment by cheton** [comment]
I won't make change in 1.9 to show/hide buttons or menu items in accordance with the connected controller board, but it can be planned in the 2.x release backlog.

**Comment by ubidefeo** [comment]
I ended up here googling for this issue with my Shapeoko 3 XL.
I find it baffling that it used to work until a few months back, I always used those UI buttons to set the work zero to start my job from, and now this error is returned.
Is it some sort of regression, @cheton ?
I swear on my name I have never used CNCjs in any other way and never had such issue
