### ISSUE TITLE
line up turn axis homing

### ISSUE THREAD

**Issue by nesquik011** [cncjs/cncjs#343]
hello , is there option to make turn axis line up by using proximity sensor ? , for example  A and B  axis  , each has proximity sensor setup somewhere , so they make full turn till they trigger the sensor  and when they trigger the sensor so they are home ? , if that option is not there may you make it please ?

**Comment by justinclift** [comment]
Hi again @nesquik011.  It sounds like you are asking about "Homing".

With many of these CNC machines, there are sensors (homing switches) on the X, Y, Z axes, as you already know about.  For the A and B axes, there is a similar thing.

It needs to be configured in your electronics, so the electronics (eg g2core or whatever) know how to drive it.

When that's working, CNCjs is able to trigger this "homing operation".  The exact command needed depends on which electronics you're using though.
