### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by JamieAKing** [cncjs/cncjs#355]
#### Description

Less of an issue but more of an annoyance. I am running cncjs on an iMac, the system is used by others in the family and also acts as a media server. As such it set to sleep after 15mins. Cncjs does not keep the system awake and 15mins in to a carve it freezes After waking the Mac a stop and restart is required (after disabling auto power saving settings!) 
Is there a way to make cncjs keep the system awake? 
#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment]
Use [Amphetamine for Mac](https://itunes.apple.com/us/app/amphetamine/id937984704?mt=12) or install & run on a Raspberry Pi.
Take a look at [cncjs-pi-raspbian (BETA)](https://github.com/cncjs/cncjs-pi-raspbian).

**Comment by scotthz** [comment]
This [docker image](https://hub.docker.com/r/scotthz/cncjs/) is another option for getting CNCjs running on a Pi. You have to install Docker on your Pi, but for me anyway, that is a lot simpler than getting dealing with the other installation options.

**Comment by MitchBradley** [comment]
@scotthz  - Just to clarify how this works: Will it still do the "npm install -g cncjs@latest --unsafe-perm" step at some point on the Raspberry Pi, albeit in a Docker container - with all of the possible observed failure modes of that step?

**Comment by scotthz** [comment]
@MitchBradley – No.  CNCjs installation is not done when the container is launched on your Raspberry Pi. I haven't used @AustinSaintAubin 's bare-metal image myself, but the concept is similar. CNCjs is already installed in the Docker image which you download.
