### ISSUE TITLE
Docker fails with ENOSPC

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#371]
#### Description

After a fresh install of Docker Toolbox on a brand new Windows 10 Home system, I tried to run cncjs and got the following error:

```
$ docker run --privileged -p 8000:8000 --rm --name cnc cncjs/cncjs:latest
<Pull complete messages elided for brevity>
[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/cnc`
2018-08-01T23:11:44.919Z - info init Loading configuration from "/root/.cncrc"
2018-08-01T23:11:45.250Z - info init Starting the server at http://172.17.0.2:8000
[nodemon] Internal watch failed: watch /proc/net/netfilter ENOSPC

```
The same thing happened with cncjs/cncjs:master-latest

#### Versions

- CNCjs:  docker image as of 2018-08-01

#### How Do You Install CNCjs?

Via Docker

#### CNC Controller

- [x] TinyG/g2core

#### Hardware

- [x] Desktop or Laptop

#### Operating System

- [x] Windows 10 Home

**Comment by MitchBradley** [comment]
The problem goes away if I start CNC directly from the docker command line, avoiding the "nodemon".

`docker run --privileged -p 8000:8000 --rm --name cnc cncjs/cncjs:latest bin/cnc`

I think this might be relevant:  https://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc

The solution might be to use "nodemon --watch " to specify only the directories that it should look at.  It's hard to imagine that watching /proc is appropriate!

**Comment by cheton** [comment]
Switching from `nodemon` to `pm2` might be a better choice for managing process.

**Comment by MitchBradley** [comment]
pm2 seems a little heavyweight.  I have found that administering pm2 is more complicated than I would prefer.

I made it work with this command:

`docker run --privileged -p 8000:8000 --rm --name cnc cncjs/cncjs:latest nodemon --watch output --watch node_modules bin/cnc`

Perhaps if cncjs were installed in a subdirectory instead of directly in the container root, that subdirectory  could be the target of --watch .

**Comment by scotthz** [comment]
I'm probably missing something, but why use nodemon in the dockerfile? Why not just 

`CMD ["/usr/local/bin/cncjs"]`

**Comment by cheton** [comment]
Nodemon is perfect for development, not mainly for production. How about using a light-weight shell script to restart process when a program exception is occurred?

```bash
#!/bin/sh

while [ 1 ]
do
    /usr/local/bin/cncjs
    sleep 1
done
```

**Comment by scotthz** [comment]
Yes, IMO nodemon is good primarily for development. In my experience, docker targets production use cases, so seeing nodemon in the container seems like it is mixing the two in an unusual way.

Docker can handle restarts if that is what you're looking for. If you don't have hidden state inside the container that you need to retain, you can add `--restart=always` when you start the container, e.g.

`docker run --detach --restart=always ...`

If you do have hidden state, maybe you can move it to a bind-mounted volume which persists after the container exits. That is a typical pattern with docker.
