### ISSUE TITLE
Travel to work position on high Z

### ISSUE THREAD

**Issue by f0m3** [cncjs/cncjs#373]
#### Description

I encountered some problems with the "move to work position" feature. Wouldn't it be better to first travel the x an y axis and after that the z axis? Moving all 3 axis at the same time can crash the router when the work position is not the highest point on the workpiece surface.

**Comment by cheton** [comment]
@f0m3 You click the gear icon ⚙️ on Axes widget, and define MDI commands for your preferred actions:

![image](https://user-images.githubusercontent.com/447801/43970478-571b510a-9d00-11e8-8acf-38259bae189f.png)
