### ISSUE TITLE
Work position not setting to Zero

### ISSUE THREAD

**Issue by wwdaves** [cncjs/cncjs#375]
#### Description

If I home my machine, the Machine Position display shows 0,0,0 as expected. If I then jog over to some position, say X=20 and click the Zero out Work Offsets, I see that a G10 L20 P1 X0 is sent as expected. However, the display still shows an X Work Position of 20. Shouldn't this read 0?

My understanding may be incorrect, but is the following: Homing the machine will set the machine coordinate system to 0. The positions may then be jogged to some arbitrary point, and then setting the work position, in this case the G54(P1) coordinate system, to 0,0,0, all Gcode coordinates sent will then be relative to the work coordinate system.

<img width="326" alt="screen shot 2018-08-14 at 7 57 17 am" src="https://user-images.githubusercontent.com/42346726/44090530-77474ad4-9f98-11e8-954e-825d07259d63.png">

- CNCjs: 1.9.16

- [ ] NPM
- [x] Download the CNCjs Desktop Application

- [ ] Grbl
- [ ] Smoothieware
- [x] TinyG/g2core

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

- [ ] Not Applicable
- [ ] Windows
- [x] Mac
- [ ] Linux

**Comment by TobyGWilliams** [comment]
Hi, 

There is a thread describing a similar situation here: https://github.com/cncjs/cncjs/issues/164

Maybe you can review the thread and see if it helps with your issue?

Many thanks
Toby
