### ISSUE TITLE
Gcode File Name

### ISSUE THREAD

**Issue by nickm324** [cncjs/cncjs#390]
#### Description

Gcode file name in 3D display is to small to even read.

#### Versions

- CNCjs: 1.9.15

![cncjsfilenamesize](https://user-images.githubusercontent.com/6774571/47608645-96346b00-d9f6-11e8-9659-9f1375e82fe2.png)

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment]
I agree. I think it would be better / nice to have the file name displayed at the top of CNCjs.
Any overflowing text could be clipped, hovering over the clipped text could show tooltip that displays the entire filename.
<img width="629" alt="screen shot 2018-10-31 at 5 38 45 pm" src="https://user-images.githubusercontent.com/969780/47822930-1549dc00-dd34-11e8-9b5f-c1eb5a7feb08.png">

**Comment by cheton** [comment]
Fixed in 1.9.17
