### ISSUE TITLE
Build process fails with socket error

### ISSUE THREAD

**Issue by atmelino** [cncjs/cncjs#395]
Just wanted to share this issue, plus the workaround.
When I run
npm run build-prod
I get the error
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
which I suspect has to do with the concurrent nature of the build process since the script is
"build-prod": "concurrently --kill-others-on-fail --names \"build-prod-app,build-prod-web\" \"npm run build-prod-app\" \"npm run build-prod-web\"",
this happens since this version of the code.
Workaround:
When I first run
npm run build-prod-app
and when it is finished, run
npm run build-prod-web
then the build process completes successfully.
Additionally, I noticed that t here are a lot of warnings in build-prod-app. Once I suppress the warnings by editing .eslintrc.js:
"rules": {
        "lines-between-class-members": "off",
        "max-lines-per-function": "off",
}
then even build-prod works. Perhaps it's a timing issue because now build-prod-app completes more quickly?
Hope this helps somebody. 

#### Versions

- CNCjs: 1.9.16-pre
- Node.js: v6.14.4
- NPM: 3.10.10

#### How Do You Install CNCjs?
clone repository
- [ ] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ X] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [ X] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [ ] Windows
- [ ] Mac
- [ X] Linux

**Comment by cheton** [comment]
It may be occurred with a bad network connection or blocked by the firewall. You can check out the wiki page that may help you resolve the compilation issue: https://github.com/cncjs/cncjs/wiki/Troubleshooting#compilation-problems
