### ISSUE TITLE
compile cncjs

### ISSUE THREAD

**Issue by snapedumbledore** [cncjs/cncjs#399]
Anyone will record a video tutorial of how to compile cncjs to .exe app?
I met a lot of problems when trying it.
If there is a video tutorial, it cann't be better.
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.15
- Node.js: 8.11.3
- NPM: 5.6.0

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by snapedumbledore** [comment]
I hope to compile cncjs source code, always failed.
After  "npm run dev", I always get the error"failed to compile".
I follow the contribution and others issue, nothing happen.
Even i reinstall node and npm and git bash.
Anyone can help me ?
There are too many error messages, so i upload 3 pictures.
#281 #332 
![cncjs1](https://user-images.githubusercontent.com/29865320/50268842-45c21280-0467-11e9-8493-458b6651eab4.png)
![cncjs2](https://user-images.githubusercontent.com/29865320/50268846-48bd0300-0467-11e9-8a5b-83155f9ae327.png)
![cncjs3](https://user-images.githubusercontent.com/29865320/50268854-4a86c680-0467-11e9-9c2c-d8f4db47347d.png)

**Comment by cheton** [comment]
https://github.com/cncjs/cncjs/wiki/Building-Instructions-on-Windows
