### ISSUE TITLE
CNCjs GUI does not update

### ISSUE THREAD

**Issue by psyreaper3** [cncjs/cncjs#470]
#### Description

I have no idea what happened, before this everything was well and good, but when i tried to change my $100, $101, $102 from 250 to 400, which should be the correct step/mm for my threaded rod, i noticed that the machine position and work position does not update as well as the 3d display, but i know it still works because when i try to run a .nc file it tries to go back to it's home position any help?

![1](https://user-images.githubusercontent.com/47425630/56850550-bce84580-6936-11e9-97d3-62f02aa6b09b.png)
![2](https://user-images.githubusercontent.com/47425630/56850551-bd80dc00-6936-11e9-8831-d87a6fcfa931.png)
![3](https://user-images.githubusercontent.com/47425630/56850784-bad3b600-6939-11e9-885e-f1e78d04da03.png)

#### Versions

- CNCjs: 1.9.18
- Node.js: 8.11.3
- NPM: 6.5.0

#### How Do You Install CNCjs?

- [] NPM
- [x ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [] Raspberry Pi
- [x ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
@psyreaper3 

https://www.facebook.com/groups/444622459677590/permalink/450761915730311/

It seems that you have resolved this issue by resetting Grbl to defaults with the reset command "$RST=*". Is it right?
