### ISSUE TITLE
Dynamically Replaceable String for host's Webcam Stream

### ISSUE THREAD

**Issue by PwnCNC** [cncjs/cncjs#471]
#### Description

The machine CNCJS is running on (in my case a Raspberry Pi) has a webcam stream as described in the manual via MJPG-Streamer.  It would be extremely convenient if you add dynamic IP address support.  If you use a special IP address "0.0.0.0" or a special string "ip" that will be replaced with the IP address of the host Raspberry Pi. For example, if the user-configured url is http://0.0.0.0:8080/, it will be replaced with http://192.168.1.1:8080/ when connecting to a webcam.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
This feature is available in CNCjs [1.9.21](https://github.com/cncjs/cncjs/releases/tag/v1.9.21)
