### ISSUE TITLE
Suggest squashing eslint warnings

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#477]
The eslint warnings about missing blank lines are getting a little tiresome.  I could submit a patch but it might be better for you to do it instead of having to review my patch.  The following will fix most of the problems in one go.

```
find src -name \*.js -o -name \*.jsx | xargs ./node_modules/.bin/eslint --fix
git commit -a -m "Squash most eslint warnings"
```
The max-lines-per-function warnings will have to be dealt with separately, if at all.

Doing this makes it a lot more pleasant to review build output for problems.

**Comment by cheton** [comment]
I will create a pull request to fix those eslint warnings. Thank you.
