### ISSUE TITLE
cannot connect Morrill

### ISSUE THREAD

**Issue by sammorrill** [cncjs/cncjs#494]
This is what happens when i try to connect. Was working fine before

CNCjs 1.9.20 [Marlin]
Connected to COM3 with a baud rate of 115200
�Np|$n�
       ~yJPOn6��Z�=a
                    ~|9L}H+MJm>F�^��s�H�X�Js�^�Q
                                               �m�7��%
&�]+mBO6wD�PH�}�MH'J�[�]�M`�<]
                              X;V�H.l�]�x�J�J�X��H3H6F
�J%�
�%�JK�J�%�
:&(^�}�$p|
�%�J�%�Ja�8z�x�:&�+^>H]�z�J�Z�K�K�KhJH'�k^>H]�Z�KqaK0�.aKk!�.a
                                                              J�j�K�J�aHJ�K�
Ov�}�6&~�
         7&?�
             ;&>�
                 ��+'
�Z�J��
^�N�8�
g
�-a*'J�J�I�N�X�:6L6N&;^f�J�[�(%�x�J�{�

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by saxa** [comment]
Seems like a baud rate issue. Try setting a lower baud rate, check parity bit, etc.
