### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by DK3GX** [cncjs/cncjs#496]
#### Description

An error always occurs when I try to  connfig user or machine-type.
 and so on.
I installed the app with adimin rights.
No idea whats wrong.

Thanks for help! Regards,
Wolfgang

![Config err](https://user-images.githubusercontent.com/47526003/60033049-1acfaa00-96a8-11e9-9134-3a480ff8040b.jpg)

#### Versions

- CNCjs: 1.9.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [ x] Desktop or **Laptop**
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x ] Windows 7 pro 64
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
I guess the app does not have access permission to write data to the `.cncrc` file under `C:\Users\MyAccount\`. Try installing the app with non-admin right, or adding write permission to the file for the current user, as shown below:

![image](https://user-images.githubusercontent.com/447801/60200431-ad26a800-9878-11e9-9bab-2cc5f74a8a5a.png)
