### ISSUE TITLE
Suggestion for an update of the rpi documentation page (and fix for Raspberry Pi Zero)

### ISSUE THREAD

**Issue by IHadToPickaUsername** [cncjs/cncjs#519]
I managed to install cncjs server on a **Raspberry Pi Zero W** (and it works great)
But following the dedicated [documentation page](https://cnc.js.org/docs/rpi-setup-guide/) gave me a little bit of a headache as I couldn't install without getting errors.

It turns out the "Install Node.js Manually" section was the issue, and simply updating version 4.5 to version 10.6.3 (which is the latest ARM6 LTS version) fixed everything.

Instead of :

# Install Node.js [Manually]

wget https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-armv6l.tar.xz
tar -xvf node-v4.5.0-linux-armv6l.tar.xz
cd node-v4.5.0-linux-armv6l
sudo cp -R * /usr/local/

It should be :

wget https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-armv6l.tar.xz
tar -xvf node-v10.16.3-linux-armv6l.tar.xz
cd node-v10.16.3-linux-armv6l
sudo cp -R * /usr/local/

I hope this helps someone

PS : As a bonus you can get cncjs with a dark theme by installing the [dark-reader](https://github.com/darkreader/darkreader) plugin on Firefox or Chrome. 

![dark-cncjs](https://user-images.githubusercontent.com/54917003/65259178-8b019680-db04-11e9-9678-3e9b757d0e63.png)

**Comment by MitchBradley** [comment]
I edited that page, but in a more complicated way.  Any time you give specific instructions that include a version number, they will be obsolete within a few months, so I tried to accommodate that.  Also, for different Pi's you need different files according to the ARM architecture.  I tried to handle that too.  It makes things more complicated to read, but at least it won't be wrong for nearly everybody (ARMv6 is the least common Pi architecture).
