### ISSUE TITLE
Electron app windows pendant mounts from command line don't work

### ISSUE THREAD

**Issue by MitchBradley** [cncjs/cncjs#551]
- CNCjs: 1.9.20
- [ X] Download the CNCjs Desktop Application
- [X ] Windows

If you edit the Target field in the CNCjs shortcut to add, say, "-m /tablet:/Users/wmb/cncjs-shopfloor-tablet/src" to the command line, you cannot later browse to the tablet pendant.  The problem is caused by the fact that slashes (`/`) are changed to backslashes (`\`).  That change is correct for the file path, but unsuitable for the "/tablet" portion.  "/tablet" is changed to "\tablet", and the URL is inaccessible.  The "View" menu has "\tablet:/Users/wmb/cncjs-shopfloor-tablet/src" instead of the correct "/tablet:/Users/wmb/cncjs-shopfloor-tablet/src"

If you use "mountPoints" in the .cncrc file to specify the pendant mount, everything works correctly.

**Comment by cheton** [comment]
Fixed in [1.9.21](https://github.com/cncjs/cncjs/releases/tag/v1.9.21)
