### ISSUE TITLE
Clarification: does not run on latest Node?

### ISSUE THREAD

**Issue by water-rhatt** [cncjs/cncjs#559]
The description says CNC.js runs on v4 and greater of Node. But it actually doesn’t run on the current version (12 at this time), correct? You MUST use v4 or v6. 

Just want to make sure I’m not missing something.

**Comment by MitchBradley** [comment]
V8 and V10 work well, but probably not v12.  I wouldn't use anything less than 8 at the present time.

**Comment by water-rhatt** [comment]
Thanks!
