### ISSUE TITLE
Changing baud rate to 921600

### ISSUE THREAD

**Issue by Plasma69** [cncjs/cncjs#567]
Hello, I need to change the baud rate of the USB ports to 921600. I run the latest version of cncjs on a raspberry pi 4. Is there anyway possible to change that.
Thank you

**Comment by Plasma69** [comment]
Can anyone help with this please?

Thank you

**Comment by cheton** [comment]
You can add a new baud rate to the `baudrates` field in the `.cncrc` file:

https://github.com/cncjs/cncjs#file-format

```
{
  "baudrates": [921600]
}
```

It will be appeared on the connection widget after restarting the CNCjs server.
