### ISSUE TITLE
Unable to configure custom widget

### ISSUE THREAD

**Issue by kebinshorts** [cncjs/cncjs#578]
#### Description

When provided the URL to a GitHub repository, the custom widget interface becomes blank. I have tried this with the "ReactApp" custom widget that came with CNCjs. In addition, I have tried publishing the repo to GitHub pages and using that URL instead, which similarly does not work. I have tried this with both NPM CNCjs and the CNCjs electron app. Am I doing something wrong?

Link to repo: https://github.com/kebinshorts/ReactApp
<img width="402" alt="blank interface" src="https://user-images.githubusercontent.com/59887703/76482611-01fc5580-63eb-11ea-99bc-f0feb24925a4.png">
<img width="563" alt="url" src="https://user-images.githubusercontent.com/59887703/76482612-058fdc80-63eb-11ea-8f53-9a0e1c4cd031.png">

#### Versions

- CNCjs: 1.9.21
- Node.js: 6.17.1
- NPM: 6.14.2

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [x] Mac
- [ ] Linux

**Comment by cheton** [comment]
https://kebinshorts.github.io/ReactApp

**Comment by kebinshorts** [comment]
The url you provided shows "no serial connection" even when the longmill is plugged in.
<img width="355" alt="Screen Shot 2020-03-12 at 9 43 45 AM" src="https://user-images.githubusercontent.com/59887703/76527686-0570fa80-6446-11ea-97b4-f659e342ecc3.png">

**Comment by cheton** [comment]
Ooops. I forgot that the path to a custom widget must be specified within the mount points.

Here is my configuration:
```js
{
    "state": {
        "checkForUpdates": true,
        "controller": {
            "exception": {
                "ignoreErrors": false
            }
        }
    },
    "mountPoints": [
        {
            "route": "/widget",
            "target": "https://cncjs.github.io/cncjs-widget-boilerplate/v1/"
        }
    ]
}
```

Also see https://github.com/cncjs/cncjs#file-format for details.

After that, set the URL field to `/widget`, you will see the content on the custom widget:

![image](https://user-images.githubusercontent.com/447801/76587918-71279600-6520-11ea-8af4-4ffa08f39093.png)
