### ISSUE TITLE
cncjs destroyed my last bit - great

### ISSUE THREAD

**Issue by phil123456** [cncjs/cncjs#587]
Hi,

- I probed the pcb before milling, yet when I ran the gcode, the bit went through it, breaking,  without even running the spindle

- hitting probe only probles localy, it does not probe the area

is there any tutorial, forum ... ?

thanks

**Comment by MitchBradley** [comment]
CNCjs User's Group on Facebook

**Comment by cheton** [comment]
For PCB milling, you can use the [Auto-leveling extension](https://github.com/kreso-t/cncjs-kt-ext) to probe the surface, it was previously discussed at https://github.com/cncjs/cncjs/issues/32#issuecomment-485240090.

For questions or operation issues, you can post it at https://www.facebook.com/groups/444622459677590/ for help.

**Comment by phil123456** [comment]
are there any tutorial besides a facebook page ?
