### ISSUE TITLE
framing feature to outline square and outline closest fit with diode laser turned on

### ISSUE THREAD

**Issue by dlarue** [cncjs/cncjs#600]
#### Description

To position your cut on a work piece those with laser cutters with aiming diodes(CO2) or especially laser diode cutter/etchers it's very handy to be able to turn the diode laser on at a low value and move the laser head around the target G-Code.  

#### Versions

- CNCjs: 1.9.22
- Node.js: 10.20.1
- NPM: 6.14.4

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by MitchBradley** [comment]
https://github.com/cncjs/cncjs/issues/455 shows a technique that can be adapted to do what you want.
