### ISSUE TITLE
Trojan detected in cncjs-app-1.9.22-win-x64.exe

### ISSUE THREAD

**Issue by korpx** [cncjs/cncjs#604]
Windows Defender claim cncjs-app-1.9.22-win-x64.exe contain Trojan:Win32/Fuery.C!cl

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fFuery.C!cl&threatid=2147718736

**Comment by AustinSaintAubin** [comment]
VirusTotal Scan. 
https://www.virustotal.com/gui/file/5f9ba28bcf7650557d216efc8aaed376e4fb55ef2529b895957a152b22578f2d

OPSWAT Meta Defender Scan.
https://metadefender.opswat.com/results/file/bzIwMDUxMmMtMVh6N2dTakxYRzZieWpDM1hr

Looks like common false positive. 
[Similar issues in the past with Sonoff ](https://github.com/itead/Sonoff_Devices_DIY_Tools/issues/27)
