### ISSUE TITLE
Prompt for Values in Macros

### ISSUE THREAD

**Issue by BernardG** [cncjs/cncjs#628]
#### Description
It would be nice if it was possible to use dialog boxes in macros to ask a value from the user. Something like this:
%TOOL_DIAMETER = window.prompt("Enter the diameter ", "6")

Thinking about a XYZ probe macro, for example, where it's needed to know the tool diameter. I am sure there would be many other applications for this.

#### Versions

- CNCjs: 1.9.22
- Node.js: 10.21.0
- NPM: 6.14.6

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x ] Linux Raspbian

**Comment by neilferreri** [comment]
Same as [this](https://github.com/cncjs/cncjs/issues/616) ?
