### ISSUE TITLE
Settings: $3=0 are not saving permanently

### ISSUE THREAD

**Issue by nolancraw** [cncjs/cncjs#639]
My Settings: $3=0 are not saving permanently when the board reboots, or if connection is re-established, this always reverts back to its defualts.

Makerverse 1.0.6

Thanks in advance !

**Comment by Fusseldieb** [comment]
All commands put into console go directly to the controller. 
This isn't CNCjs' fault.

**Comment by emcniece** [comment]
Closing as off-topic, cheers!
