### ISSUE TITLE
docker install error on Pi 4: exec format error

### ISSUE THREAD

**Issue by jairusmartin** [cncjs/cncjs#644]
#### Description

I am installing CNCjs via Docker on the Pi 4.

When I run:
 `docker run --privileged -p 8000:8000 --rm --name cncjs cncjs/cncjs:latest`

I get:
 `standard_init_linux.go:211: exec user process caused "exec format error"`

![image](https://user-images.githubusercontent.com/15862942/93688842-f9ba5c80-fa96-11ea-9646-eb71a8d4d8b5.png)

#### Versions

- docker cncjs/cncjs : v1.9.20

#### How Do You Install CNCjs?

- [x] Docker

#### CNC Controller

- [x] TinyG/g2core

#### Hardware

- [x] Raspberry Pi

#### Operating System

- [x ] Linux

**Comment by MitchBradley** [comment]
The supported method for installing CNCjs on Raspberry Pi is as described in https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Package-Manager-*(Recommended)* .  The Docker instructions say "x64 only", so the Docker image is almost certainly for a PC with an Intel processor, not the ARM processor on a Raspberry Pi.  It would probably be possible to create a Docker image for a Pi, but it someone has done that, none of the active CNCjs support people are maintaining it.
