### ISSUE TITLE
connection via ethernet to smoothie board

### ISSUE THREAD

**Issue by augustenlee** [cncjs/cncjs#653]
#### Description

HI, Sir,
I use a smoothieware board and connected by Ethernet
but on the APP screen Port setting can just only be set as USB ports
how can I make connection to my smoothie ware board via Ethernet?
Thanks a lot 

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [ ] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [ ] Grbl
- [x] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [x] Mac
- [ ] Linux

**Comment by MitchBradley** [comment]
CNCjs does not support Ethernet connections to controllers.
