### ISSUE TITLE
Using ethernet connection on mks sbase

### ISSUE THREAD

**Issue by Wifiunterputzdose** [cncjs/cncjs#674]
#### Description

Is it possible to use cnc.js with the mks sbase v1.3 trough the ethernet connection?

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [x] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device
- [x] MKS SBASE v1.3

#### Operating System

- [] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by MitchBradley** [comment]
No.  CNCjs only connects to controllers via serial.
