### ISSUE TITLE
Restart a file from a pourcentage ?

### ISSUE THREAD

**Issue by Franckapik** [cncjs/cncjs#694]
#### Description

I would like to know if it's possible to resume a file at certain % when an error occur for example near the end of the cut process ? 
In my situation, i have sometime some electrical shut down. And i would like to know if i can restart the file by saying "go directly to this gcode line" ?

Thank you by the way for this great works !
#### Versions

- CNCjs: 1.9.22

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

**Comment by MitchBradley** [comment]
No. That feature has been requested a few times but it is tricky to implement.
