### ISSUE TITLE
Prompt user to choose the units option if it's not available in the G-code file

### ISSUE THREAD

**Issue by cheton** [cncjs/cncjs#70]
If it cannot determine whether a G-code file should run in G20 (inches) or G21 (mm), prompt user to choose the units option to make sure the job will cut at the proper size.

This feature is already available in ChiliPeppr, like below:
![image](https://cloud.githubusercontent.com/assets/447801/18374688/961f301c-7681-11e6-8d7e-cce2e57d6dce.png)

**Comment by AustinSaintAubin** [comment]
I recommend doing It differently than chili pepper. 
Popups are annoying.
I recommend having an option in settings or on the center preview widgit to change matric or imperial would be nice.

**Comment by cheton** [comment]
This is not a necessary feature because user can change units on the UI anytime. I will close this issue.
