### ISSUE TITLE
CNCJs Wont start, installed correctly on RPI4

### ISSUE THREAD

**Issue by raptorfa22** [cncjs/cncjs#713]
#### Description

I was able to install CNCjs on my raspberry pi 4 and upon reboot I get the popup screen stating that the server is starting and with the directions on how to exit to chrome kiosk and to exit the UI. After clicking ok on this popup nothing happens. I have even tried opening from a web browser on another computer. I will be using CNCjs to control a Genmitsu 3018 pro with the y axis extension to a 3040 setup.

Micro SD card used:
SanDisk 128GB Extreme microSDXC UHS-I Memory Card with Adapter - Up to 160MB/s, C10, U3, V30, 4K, A2, Micro SD - SDSQXA1-128G-GN6MA

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?
Installed using the following:
URL="https://raw.githubusercontent.com/cncjs/cncjs-pi-raspbian/master/cncjs_install.sh"
curl -sSL ${URL} | bash

A00 through A07 were selected during installation from the splash screen
All pendant and widget options in the splash screen were selected

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by MitchBradley** [comment]
Please refile the bug report in the cncjs-pi-raspbian issues section.
