### ISSUE TITLE
Limit travel based on relative axis location - feature request

### ISSUE THREAD

**Issue by StaticKling** [cncjs/cncjs#724]
#### Only allow travel up to machines area

I've mistakenly under estimated the jogging distance a few times and ended up grinding the gears on the machine.  I've tried searching the issues/feature requests and didn't come up with any results for something like this. I would think that one could set default measurements for the x,y,z travel (machine settings widget?) and when a jogging step is executed, perform a calculation:
 
function axisLimitCheck(axis, distance){
// axis is either x, y, z, whichever jogging button was clicked
// distance is the selected jog distance (-/+)

if (axis.location > (current position + distance )) { 
    // execute 
}
 else if (axis.location < (current position + distance))
{
 // Alert warning and prompt to jog only up to max area of machine
}

If this exists already, sweet!  if not, thanks for the consideration.

**Comment by MitchBradley** [comment]
This feature is commonly available in controller firmware - for example grbl.  It is called "soft limits".  You need to enable it there.
