### ISSUE TITLE
Auto-squaring on XYYZ machine with dual Y limit switches

### ISSUE THREAD

**Issue by ausip** [cncjs/cncjs#725]
#### Description

I can't seem to get my machine initialisation Macro correct to allow auto-squaring using dual Y-Axis limit switches on an XYYZ machine.

Is this possible?
If so, how do I modify my Macro to support this functionality?

Here is my initialisation Macro

$Homing/Cycle0=Z
$Homing/Cycle1=XY
$Stepper/Pulse=5
$Stepper/IdleTime=255
$Stepper/DirInvert=X
$Stepper/EnableInvert=Off
$Limits/Invert=On
$Probe/Invert=Off
$Report/Status=1
$Limits/Hard=On
$Homing/Enable=On
$Homing/DirInvert=XY
$Homing/Feed=100.000
$Homing/Seek=1000.000
$Homing/Pulloff=10.000
$X/StepsPerMm=200.000
$Y/StepsPerMm=200.000
$Z/StepsPerMm=200.000
$A/StepsPerMm=200.000
$X/MaxRate=3000.000
$Y/MaxRate=3000.000
$Z/MaxRate=2500.000
$A/MaxRate=3000.000
$X/Acceleration=150.000
$Y/Acceleration=150.000
$Z/Acceleration=150.000
$A/Acceleration=150.000
$X/MaxTravel=1250.00
$Y/MaxTravel=810.00
$Z/MaxTravel=210.00
$A/MaxTravel=810.00
$X/Current/Run=1.950
$Y/Current/Run=1.950
$Z/Current/Run=1.950
$A/Current/Run=1.950
$X/Current/Hold=1.250
$Y/Current/Hold=1.250
$Z/Current/Hold=1.250
$A/Current/Hold=1.250
$X/Microsteps=8
$Y/Microsteps=8
$Z/Microsteps=8
$A/Microsteps=8

#### Versions

- CNCjs: 1.9.23

#### How Do You Install CNCjs?

- [x] NPM

#### CNC Controller

- [x] Grbl (Pro V5)

#### Hardware

- [x] Raspberry Pi

**Comment by MitchBradley** [comment]
Auto squaring is not a function of CNCjs, but rather a function of the controller firmware.  Please contact the vendor of your xPro V5 controller for help in setting up its firmware.  In general, it is best to ask for support from the vendor who took your money, instead of from the people who supply software at no cost.
