### ISSUE TITLE
Connection via network 192.168.0.1 at port 23 

### ISSUE THREAD

**Issue by ashokavarthanan** [cncjs/cncjs#779]
#### Description

Connection via network 192.168.0.1 at port 23.
option not in connection widget.
how can connect ?

ESP32-grbl

**Comment by Witawat** [comment]
use Tibbo VSP Manager 
![dlc32-cncjs](https://user-images.githubusercontent.com/4926369/196891920-041c0986-b1ee-4035-a321-2c107eab23df.gif)

**Comment by ashokavarthanan** [comment]
Thanks. it works.
