### ISSUE TITLE
Homing issues and Z axis

### ISSUE THREAD

**Issue by mjadams61** [cncjs/cncjs#788]
I just bought the CNC xpro V5 and I am having trouble homing. Now I can touch off the XYZ buttons and everything is fine , but when I try to home it does is does every backward and I am using openbuilds software

**Comment by MitchBradley** [comment]
Ask the people who sold you the xpro, not the unpaid volunteers who maintain cncjs.  Your problem has nothing at all to do with cncjs and everything to do with the xpro.
