### ISSUE TITLE
How to run g-code X number of times using macro?

### ISSUE THREAD

**Issue by ashokavarthanan** [cncjs/cncjs#841]
I have to run g-code to 100 times with every 3 seconds pause. 
Like "for" loop or "while" loop.
Thanks.

**Comment by rflulling** [comment]
This will not work in all Firmware. 

Marlin Firmware at some point added function M808
https://marlinfw.org/docs/gcode/M808.html

This will allow loops. 

Sorry now idea what this will look like or if it is available at all in other firmwares.
