### ISSUE TITLE
"No ports available"

### ISSUE THREAD

**Issue by M-Tie** [cncjs/cncjs#847]
#### Description

 Hi, I'm trying to connect my PC to an xPROv5 with the CNCjs app through USB but it keeps telling me that no ports are available. I've been using the CNCjs app for 2 years with no issues on windows 10, but I recently bought a new PC with windows 11, and now I can't connect to the machine. I've tried to install older CNCJS versions and upgrade the USB drivers but nothing works. I can still control the machine through the xPROv5 web interface but I really prefer the CNCjs app.
If someone has an idea, that'd be very helpful !

#### Versions

- CNCjs: 1.10.2
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [] NPM
- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [x] Windows
- [ ] Mac
- [ ] Linux

**Comment by thijstriemstra** [comment]
Maybe COM port changed?

**Comment by cheton** [comment]
@M-Tie 
Check out https://forum.arduino.cc/t/windows-11-device-manager-does-not-show-esp32-with-cp2102/1160075
