### ISSUE TITLE
question: custom widgets

### ISSUE THREAD

**Issue by MoonshineSG** [cncjs/cncjs#85]
any chance that in the (near) future we can have teh ability to write custom widgets ? 
say, a simplified "axes" in my case...

**Comment by AustinSaintAubin** [comment]
There is already that ability. Have a look at [tinyweb](https://github.com/cheton/cnc/wiki/User-Guide#tinyweb-console-on-320x240-lcd-display).

**Comment by MoonshineSG** [comment]
i did see that one and it's an awesome feature, but not not what I had in mind.... 
Not to replace the whole UI, but on the main UI an additional,  custom widget.

**Comment by cheton** [comment]
Custom widget support is now available in 1.9.10.
