### ISSUE TITLE
General 

### ISSUE THREAD

**Issue by AMunirudeen** [cncjs/cncjs#865]
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions
![Screenshot_20240614-174913](https://github.com/cncjs/cncjs/assets/172840401/8d18d077-f1f4-4c79-b168-d65a7d2bc22f)

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AMunirudeen** [comment]
![Screenshot_20240614-181055_1](https://github.com/cncjs/cncjs/assets/172840401/90587600-6b7e-44a0-8f7d-b8051f161dc0)

**Comment by AMunirudeen** [comment]
Write a g-code for machining the component attached on the CNC milling machine.

**Comment by MitchBradley** [comment]
This is not a CNCjs software issue.  We do not provide gcode authoring services.
