### ISSUE TITLE
Write a g-code for machining the component attached on the CNC milling machine.

### ISSUE THREAD

**Issue by AMunirudeen** [cncjs/cncjs#866]
![Screenshot_20240614-181055_1](https://github.com/cncjs/cncjs/assets/172840401/d5bbcb69-5c1b-4af5-ad1e-7f1c3b816b8d)
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by ril3y** [comment]
LOL is this a request for and issue to write gcode?
