### ISSUE TITLE
conflicting shortcut key assignment in combokeys.js

### ISSUE THREAD

**Issue by rusttick** [cncjs/cncjs#873]
#### Description

The ctrl+alt+command+b shortcut key is assigned conflicting tasks in combokeys.js. 

1. select the b axis
2. jog backward

```
$ grep \'command\'\,\ \'b ./src/app/lib/combokeys.js
    keys: ['ctrl', 'alt', 'command', 'b'].join('+'),
    keys: ['ctrl', 'alt', 'command', 'b'].join('+'),
```

```
  { // Jog Backward (Alias)
    keys: ['ctrl', 'alt', 'command', 'b'].join('+'),
    cmd: 'JOG',
    payload: {
      axis: null,
      direction: BACKWARD,
      factor: 1
    },
    preventDefault: true
  },
```

```
  { // Select B-axis
    keys: ['ctrl', 'alt', 'command', 'b'].join('+'),
    cmd: 'SELECT_AXIS',
    payload: {
      axis: 'b'
    },
    preventDefault: true
  },
```

Please pick another letter. A letter is preferred as https://github.com/abourget/shuttle-go will not accept "command+[" when defining key bindings for some reason... regardless... there should not be conflicting assignments in combokeys.js

Thanks for your time reviewing this issue! It's not an emergency or anything... just putting it on your radar for later versions. Thanks again for the fantastic app!

#### Versions

- CNCjs: 1.10.3
- Node.js: 20.10.0
- NPM: 10.2.3

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [ ] Not Applicable
- [ ] Windows
- [ ] Mac
- [x] Linux

**Comment by cheton** [comment]
Resolved in PR https://github.com/cncjs/cncjs/pull/875
